# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "../scripts", "/scripts"

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    export STELLAR_CORE_VERSION=#{ENV['STELLAR_CORE_VERSION']}
    sudo apt-get update
    sudo -E /scripts/create_stellar_user.sh
    sudo -E /scripts/install_stellar_core.sh
    sudo -E /scripts/setup_postgres.sh
    sudo -E /scripts/runtime_c_libs.sh
    sudo -E /scripts/configure_sdf_peer.sh
    sudo -E /scripts/clean_disk_space.sh
  SHELL

  config.vm.post_up_message = <<-MESSAGE
    All done!

    Now run this to package it at a box for upload:

        vagrant package --output stellar-core-base.box
  MESSAGE
end
